name: flutter_note_app
description: Flutter Note App
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.0
  google_fonts:
  sqflite:
  flutter_staggered_grid_view: ^0.4.0
  intl:
  get_storage: ^2.0.3
  local_auth: ^1.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg